[package]
name = "longer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive", "suggestions", "color"] }
chrono = "0.4"
thiserror = "1.0.40"
prettytable-rs = "0.10.0"

